#!/usr/bin/env python3
"""Builds ChiaKey-Source/DataTables/emoji-zh-hant.txt from Unicode data.

Sources (both under the Unicode License v3):
  - CLDR Traditional Chinese emoji annotations (names and keywords)
  - emoji-test.txt, for the fully-qualified form of each emoji

Output, one keyword per line:  <keyword>\t<emoji> <emoji> ...
Emoji whose CLDR name is the keyword come first, then the rest in Unicode's
own order. Keywords shared by too many emoji (e.g. 臉, "face") are left out:
offered as candidates they would bury the useful ones.

Run it again to pick up a newer CLDR release; the build does not need network.
"""

import json
import re
import sys
import urllib.request
from pathlib import Path

CLDR_PACKAGE = "https://cdn.jsdelivr.net/npm/cldr-annotations-full"
ANNOTATIONS_URL = f"{CLDR_PACKAGE}/annotations/zh-Hant/annotations.json"
PACKAGE_URL = f"{CLDR_PACKAGE}/package.json"
EMOJI_TEST_URL = "https://unicode.org/Public/emoji/latest/emoji-test.txt"

MAX_EMOJI_PER_KEYWORD = 12   # broader keywords are dropped
MAX_LISTED_PER_KEYWORD = 8   # how many a kept keyword offers
SKIN_TONES = re.compile("[\U0001F3FB-\U0001F3FF]")
CJK = re.compile("[㐀-鿿豈-﫿]")

OUTPUT = (Path(__file__).resolve().parent.parent / "ChiaKey-Source" /
          "DataTables" / "emoji-zh-hant.txt")


def fetch(url):
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read().decode("utf-8")


def fully_qualified_emoji(emoji_test):
    """Maps each emoji without U+FE0F to its fully-qualified form, in order."""
    result = {}
    version = ""
    for line in emoji_test.splitlines():
        if line.startswith("# Version:"):
            version = line.split(":", 1)[1].strip()
        if "; fully-qualified" not in line:
            continue
        codepoints = line.split(";", 1)[0].split()
        emoji = "".join(chr(int(cp, 16)) for cp in codepoints)
        if SKIN_TONES.search(emoji):
            continue  # the base emoji stands for its skin-tone variants
        result.setdefault(emoji.replace("️", ""), emoji)
    return result, version


def main():
    package = json.loads(fetch(PACKAGE_URL))
    annotations = json.loads(fetch(ANNOTATIONS_URL))["annotations"]["annotations"]
    qualified, emoji_version = fully_qualified_emoji(fetch(EMOJI_TEST_URL))
    order = {emoji: index for index, emoji in enumerate(qualified.values())}

    named = {}      # keyword -> emoji whose CLDR name it is
    keyworded = {}  # keyword -> emoji it is one of the keywords of
    for key, entry in annotations.items():
        emoji = qualified.get(key.replace("️", ""))
        if not emoji:
            continue  # CLDR also annotates plain symbols such as arrows
        for keyword in entry.get("tts", []):
            named.setdefault(keyword, []).append(emoji)
        for keyword in entry.get("default", []):
            keyworded.setdefault(keyword, []).append(emoji)

    lines = []
    for keyword in sorted(set(named) | set(keyworded)):
        if not CJK.search(keyword) or re.search("[A-Za-z0-9]", keyword):
            continue
        everything = set(named.get(keyword, [])) | set(keyworded.get(keyword, []))
        if len(everything) > MAX_EMOJI_PER_KEYWORD:
            continue
        ranked = sorted(everything,
                        key=lambda e: (e not in named.get(keyword, []), order[e]))
        lines.append(keyword + "\t" + " ".join(ranked[:MAX_LISTED_PER_KEYWORD]))

    header = [
        "# Emoji candidates for Traditional Chinese keywords.",
        f"# Generated by Scripts/generate-emoji-table.py from Unicode CLDR "
        f"{package['version']} (zh-Hant annotations) and Emoji {emoji_version}.",
        "# Copyright © 1991-2025 Unicode, Inc. Licensed under the Unicode License v3:",
        "# https://www.unicode.org/license.txt",
        "# Format: <keyword>\\t<emoji> <emoji> ...",
    ]
    OUTPUT.write_text("\n".join(header + lines) + "\n", encoding="utf-8")
    print(f"wrote {len(lines)} keywords to {OUTPUT}")


if __name__ == "__main__":
    sys.exit(main())
